import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { ClerkProvider, SignedIn, SignedOut, SignInButton, UserButton } from "@clerk/nextjs";

import '@mantine/core/styles.css';
import { AppShell, ColorSchemeScript, MantineProvider, Burger } from '@mantine/core';
import { PressStartShell } from "~/_components/PressStartShell";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [ { rel: "icon", url: "/favicon.ico" } ],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {

  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <head>
        <ColorSchemeScript />
      </head>
      <ClerkProvider>
        <MantineProvider>

          <body>
            <PressStartShell >
              {children}
            </PressStartShell >
          </body>
        </MantineProvider>
      </ClerkProvider>
    </html>
  );
}
